spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: pneumo
    password: Secu30rity@#
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8060
