spring:
  application:
    name: affable-bean-backend-service
  datasource:
    url: jdbc:mysql://localhost:3306/affable_backend
    username: pneumo
    password: Secu30rity@#
  jpa:
    hibernate:
      ddl-auto: update



